name: ChangeDetection.io
version: 0.51.1
slug: changedetection
description: Website change detection, web page monitoring, and website change alerts.
url: https://github.com/Eskander/haos-apps
image: ghcr.io/dgtlmoon/changedetection.io
legacy: true
arch:
  - amd64
  - aarch64
init: false
webui: http://[HOST]:[PORT:5000]/
environment:
  HIDE_REFERER: "true"
  DISABLE_VERSION_CHECK: "true"
  USE_X_SETTINGS: "1"
options:
  PLAYWRIGHT_DRIVER_URL: "ws://ec6f6e63-sockpuppetbrowser:3000"
schema:
  PLAYWRIGHT_DRIVER_URL: str
  SCREENSHOT_MAX_HEIGHT: int?
ports:
  5000/tcp: 5000
map:
  - type: data
    path: /datastore
    read_only: false
