name: ArchiSteamFarm
version: "6.3.0.2"
slug: archisteamfarm
description: C# application with primary purpose of farming Steam cards from multiple accounts simultaneously
url: https://github.com/Eskander/haos-apps
image: ghcr.io/eskander/haos-archisteamfarm
arch:
  - amd64
  - aarch64
init: false
ingress: true
ingress_port: 1242
panel_icon: mdi:steam
options:
  cryptkey: ""
schema:
  cryptkey: password?
ports:
  1242/tcp: null
map:
  - type: addon_config
    path: /app/config
    read_only: false
  - type: data
    path: /app/logs
    read_only: false
